# Generated by Django 6.0.7 on 2026-07-10 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeupload',
            name='extracted_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resumeupload',
            name='found_sections',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='resumeupload',
            name='found_skills',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='resumeupload',
            name='has_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resumeupload',
            name='has_phone',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resumeupload',
            name='missing_sections',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='resumeupload',
            name='score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resumeupload',
            name='suggestions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='resumeupload',
            name='word_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
